#!/bin/sh

echo "Building for Windows ..."
GOOS=windows go build -o client/windows/calc.exe src/calc/calc.go

echo "Building for Mac (darwin) ..."
GOOS=darwin go build -o client/mac/calc src/calc/calc.go

echo "Building for Linux ..."
GOOS=linux go build -o client/linux/calc src/calc/calc.go
